### ISSUE TITLE
error C2440

### ISSUE THREAD

**Issue by VladimirPobedinskiy** [loreglean/lantern#5] opened 2015-02-23 05:29 UTC
error C2440: <function-style-cast>: невозможно преобразовать "initializer-list" в "lantern::shader_bind_point_info<lantern::color>"	
e:\Projects\lantern-master\lantern\include\color_shader.h (строка 85)
rasterized_triangle_app

Visual Studio 2013 Ultimate

**Comment by loreglean** [comment] 2015-02-23 20:22
I don't have an ultimate edition, but it compiles fine on Community 2013. Do you know what difference causes that?

**Comment by VladimirPobedinskiy** [comment] 2015-02-24 07:36
I make some changes:
Added constructor to shader_bind_point_info class - shader.h
```
	template<typename TAttr>
	class shader_bind_point_info
	{
	public:
		shader_bind_point_info(unsigned int attribute_id_, TAttr* bind_point_)
			: attribute_id{ attribute_id_ }, bind_point{ bind_point_ }
		{
		}

		/** Attribute id */
		unsigned int attribute_id;

		/** Address to put value into */
		TAttr* bind_point;
	};
```

pipeline.h (20)
```
	class binded_mesh_attribute_info final
	{
	public:
		binded_mesh_attribute_info(mesh_attribute_info<TAttr> const& info_, TAttr* bind_point_)
			: info{ info_ }, bind_point{ bind_point_ }
		{
		}

		/** Attribute data */
		mesh_attribute_info<TAttr> const& info;

		/** Address of variable to put interpolated value into */
		TAttr* bind_point;
	};
```

Change color_shader::get_color_bind_points() method to this code
```
	inline std::vector<shader_bind_point_info<color>> color_shader::get_color_bind_points()
	{
		return std::vector<shader_bind_point_info<color>>
		{
			shader_bind_point_info<color>(VERTEX_COLOR_ATTR_ID, &m_color)
		};
	}
```

pipeline.h (473)
```
binded_attributes_storage.push_back(
	binded_mesh_attribute_info<TAttr>(attr_info, bind_point_info.bind_point));
```

**Comment by loreglean** [comment] 2015-07-19 20:06
I'm closing this because I can't reproduce it. If you'll have more information feel free to create a new one

**Closed by loreglean** 2015-07-19 20:06 UTC
